name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        mkdocs --version
    - name: Build
        mkdocs build
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      if: github.event_name == 'push' && github.ref == 'master'
      env:
        BUILD_DIR: "site/"
      secrets:
        GH_PAT

